# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azbutils < Formula
  desc "gsutil-like CLI for Azure Blob Storage."
  homepage "https://github.com/orionnectar/homebrew-tools"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orionnectar/go-azbutils/releases/download/v0.1.6/azbutils_darwin_amd64.tar.gz"
      sha256 "c13dfe0118a3ba373581154044c178c960507fb7b89fadb3b555b2181edbbf92"

      def install
        bin.install "azbutils"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orionnectar/go-azbutils/releases/download/v0.1.6/azbutils_darwin_arm64.tar.gz"
      sha256 "21bd6f1c3ba576c528c4431e8cd60006e402b660a67581d00c3d6e4b943a2c1a"

      def install
        bin.install "azbutils"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orionnectar/go-azbutils/releases/download/v0.1.6/azbutils_linux_amd64.tar.gz"
      sha256 "28452480cbce1cb293265d0701213d5277dd09283156adcaf73f6713715c60db"
      def install
        bin.install "azbutils"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orionnectar/go-azbutils/releases/download/v0.1.6/azbutils_linux_arm64.tar.gz"
      sha256 "d7acdc93e62f4ae0eb697b6b702a4f230fddbf3e90c1ccab15e167147bdf870a"
      def install
        bin.install "azbutils"
      end
    end
  end

  test do
    system "#{bin}/azbutils", "--version"
  end
end
