# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azbutils < Formula
  desc "gsutil-like CLI for Azure Blob Storage."
  homepage "https://github.com/orionnectar/homebrew-tools"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orionnectar/go-azbutils/releases/download/v0.1.5/azbutils_darwin_amd64.tar.gz"
      sha256 "fb34d099229597871e0b1cd65c67383d28fcd0df01763e72e7d31eed38ecc367"

      def install
        bin.install "azbutils"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orionnectar/go-azbutils/releases/download/v0.1.5/azbutils_darwin_arm64.tar.gz"
      sha256 "e620a8b40646198668213bdbbd0c551987382271cb7e599ae75c0889aa81bfce"

      def install
        bin.install "azbutils"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orionnectar/go-azbutils/releases/download/v0.1.5/azbutils_linux_amd64.tar.gz"
      sha256 "cb2f157bb7da8bef0433852d8b51561fbf1ab6cbf19504bfdf69d0a0505e89c9"
      def install
        bin.install "azbutils"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orionnectar/go-azbutils/releases/download/v0.1.5/azbutils_linux_arm64.tar.gz"
      sha256 "a3d09e0af71170d10ded53bcbb577fb778373d48adf7029b18c0e9fd18bcb55e"
      def install
        bin.install "azbutils"
      end
    end
  end

  test do
    system "#{bin}/azbutils", "--version"
  end
end
